# Numpy
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Numpy is faster in reading and writing items compared with Python lists.
[StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists)


In [1]:
import numpy as np

## Create An Numpy Array

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

## Matrix Comparison

In [3]:
# Matrix
matrix1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [4]:
matrix1

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [5]:
# Numpy matrix
np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Built-in Methods
### rand
**Distribution**: Uniform Distribution <br/>

In [6]:
np.random.rand(4)

array([0.20662603, 0.09827914, 0.965551  , 0.67551633])

In [7]:
np.random.rand(4,4)

array([[0.67169617, 0.85929647, 0.54596066, 0.36495795],
       [0.86187378, 0.62265394, 0.73591065, 0.52801415],
       [0.15819413, 0.97254657, 0.68708917, 0.78790293],
       [0.54279007, 0.23047312, 0.63575121, 0.30574388]])

### randn
**Distribution**: follow Standard Normal Distribution <br/>

In [8]:
np.random.randn(2)

array([-0.31889826, -0.06684682])

In [9]:
np.random.randn(5,5)

array([[-0.80955239,  0.61801355, -0.04148235,  1.15023019,  0.79540548],
       [ 0.86074606, -0.23435152,  0.46489274, -0.27343943,  0.2670921 ],
       [ 1.12387596, -1.28291999, -1.84688836,  2.34724146, -0.74424678],
       [ 1.20125016, -1.2413297 ,  1.35451767, -0.23555545,  1.71720172],
       [ 0.71720123,  0.17927637,  0.24038592, -0.60799248, -1.76560144]])

### randint

In [10]:
np.random.randint(1,10)

8

In [11]:
np.random.randint(1,50,5)

array([ 3,  2, 47, 12, 21])

## Useful Attributes & Methods

### Reshape

In [12]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [13]:
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### max, min, argmax, argmin

In [15]:
arr1.max()

10

In [16]:
arr1.min()

1

In [17]:
#.argmax() find the index for max
arr1.argmax()

9

In [18]:
#.argmin() find the index for min
arr1.argmin()

0

### shape

In [19]:
arr1.shape

(10,)

In [20]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr2 = arr1.reshape(2,5)

In [22]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

sum is a method. Methods should be called. To call a function or method you need the (). <br/>
shape is a property (but could also be an attribute) and you don't need to call those! 

In [23]:
arr2.shape

(2, 5)

In [24]:
arr2.sum()

55

### concatenate

In [25]:
a = np.array([[2,3], [3,4]])

In [26]:
b = np.array([[5,6]])

In [27]:
a # a is a 2 by 2 numpy matrix

array([[2, 3],
       [3, 4]])

In [28]:
b # b is a 1 by 2 numpy matrix

array([[5, 6]])

In [29]:
np.concatenate((a, b), axis = 0) # concatenate a and by by 0, by rows, add b as a row to the end of a

array([[2, 3],
       [3, 4],
       [5, 6]])

In [30]:
np.concatenate((a, b), axis = 1) # axis = 1 means concatenate by column, we have a which is 2 by 2, we have b which is 1 by 2, so we have to make b looks like
# 2 by 1. so we need to adjust b to b transpose

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [31]:
# b transpose: b.T
b.T

array([[5],
       [6]])

In [32]:
np.concatenate((a, b.T), axis = 1)

array([[2, 3, 5],
       [3, 4, 6]])

In [33]:
# We can also set axis to None
np.concatenate((a, b), axis = None) # This is no longer a matrix, it's a numpy array

array([2, 3, 3, 4, 5, 6])

In [34]:
# We can also concatenate multiple numpy arrays
a1 = np.array([1,2,3,4])
a2 = np.array([4,5,6,7])
a3 = np.array([3,2])

In [35]:
np.concatenate((a1,a2,a3), axis = None)

array([1, 2, 3, 4, 4, 5, 6, 7, 3, 2])